name: church-comms

services:
  postgres:
    container_name: church-comms-postgres
    image: postgres:18.4
    hostname: church-comms-postgres
    environment:
      POSTGRES_DB: church_comms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

volumes:
  postgres-data:
